name: Scan Jobs Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"  # Runs daily at 09:00 UTC 

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install chromium

      - name: Run script
        run: python program.py

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: job-scan-results
          path: results/jobs_found.txt

      - name: Send email with results
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: swsorour@hotmail.com
          password: ${{ secrets.HOTMAIL_PASSWORD }}
          subject: "Job Scan Results"
          body: "Please find the attached job scan results."
          to: swsorour@hotmail.com
          from: swsorour@hotmail.com
          attachments: results/jobs_found.txt