name: Scan Jobs Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 1,3,5"  # Runs at 09:00 UTC Mon/Wed/Fri

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install chromium
          pip install reportlab

      - name: Run script
        run: python program.py

      - name: Prepare results for GitHub Pages
        run: |
          mkdir output
          cp results/jobs_found.txt output/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: deploy